### ISSUE TITLE
aidl ip010 gazebo issue 

### ISSUE THREAD

**Issue by ghost** [kimsooyoung/AIDL_ip010_lecture#1]
navigation2 ppt 에서 15페이지의 slam 작업 진행 중  
Terminal 1 – AWS Warehouse Gazebo 실행
ros2 launch ip010_gazebo factory_world.launch.py   
를 실행 할 때에 다음과 같은 에러가 발생하면서 가제보가 실행이 되지 않습니다.

^C(ROS 2 foxy) aidl@aidl-TFG5597XG:~/aidl_ws$ ros2 launch ip010_gazebo factory_world.launch.py
[INFO] [launch]: All log files can be found below /home/aidl/.ros/log/2022-07-28-16-07-51-117347-aidl-TFG5597XG-3074
[INFO] [launch]: Default logging verbosity is set to INFO
 If it's your 1st time to download Gazebo model on your computer, it may take few minutes to finish. 
[INFO] [gzserver-1]: process started with pid [3076]
[INFO] [gzclient   -2]: process started with pid [3079]
[INFO] [robot_state_publisher-3]: process started with pid [3082]
[INFO] [joint_state_publisher-4]: process started with pid [3084]
[INFO] [spawn_entity.py-5]: process started with pid [3086]
[robot_state_publisher-3] 1658992071.591794 [30] robot_stat: using network interface wlp4s0 (udp/192.168.0.13) selected arbitrarily from: wlp4s0, docker0
[robot_state_publisher-3] Parsing robot urdf xml string.
[robot_state_publisher-3] Link base_link had 6 children
[robot_state_publisher-3] Link center_lidar had 0 children
[robot_state_publisher-3] Link front_ballcaster had 0 children
[robot_state_publisher-3] Link front_camera had 0 children
[robot_state_publisher-3] Link imu_link had 0 children
[robot_state_publisher-3] Link l_rear_wheel had 0 children
[robot_state_publisher-3] Link r_rear_wheel had 0 children
[robot_state_publisher-3] [INFO] [1658992071.598429479] [robot_state_publisher]: got segment base_footprint
[robot_state_publisher-3] [INFO] [1658992071.598514968] [robot_state_publisher]: got segment base_link
[robot_state_publisher-3] [INFO] [1658992071.598523263] [robot_state_publisher]: got segment center_lidar
[robot_state_publisher-3] [INFO] [1658992071.598528122] [robot_state_publisher]: got segment front_ballcaster
[robot_state_publisher-3] [INFO] [1658992071.598532400] [robot_state_publisher]: got segment front_camera
[robot_state_publisher-3] [INFO] [1658992071.598536588] [robot_state_publisher]: got segment imu_link
[robot_state_publisher-3] [INFO] [1658992071.598540686] [robot_state_publisher]: got segment l_rear_wheel
[robot_state_publisher-3] [INFO] [1658992071.598544793] [robot_state_publisher]: got segment r_rear_wheel
[gzserver-1] 1658992071.780737 [30]   gzserver: using network interface wlp4s0 (udp/192.168.0.13) selected arbitrarily from: wlp4s0, docker0
[joint_state_publisher-4] 1658992071.843227 [30] joint_stat: using network interface wlp4s0 (udp/192.168.0.13) selected arbitrarily from: wlp4s0, docker0
[spawn_entity.py-5] 1658992071.845949 [30]    python3: using network interface wlp4s0 (udp/192.168.0.13) selected arbitrarily from: wlp4s0, docker0
[spawn_entity.py-5] [INFO] [1658992071.882206647] [spawn_entity]: Spawn Entity started
[spawn_entity.py-5] [INFO] [1658992071.882428741] [spawn_entity]: Loading entity published on topic robot_description
[spawn_entity.py-5] [INFO] [1658992071.884551855] [spawn_entity]: Waiting for entity xml on robot_description
[joint_state_publisher-4] [INFO] [1658992071.884569989] [joint_state_publisher]: Waiting for robot_description to be published on the robot_description topic...
[spawn_entity.py-5] [INFO] [1658992071.887084552] [spawn_entity]: Waiting for service /spawn_entity, timeout = 30
[spawn_entity.py-5] [INFO] [1658992071.887275808] [spawn_entity]: Waiting for service /spawn_entity
[gzserver-1] [WARN] [1658992072.130994577] [rcl]: Found remap rule 'model_states:=model_states_demo'. This syntax is deprecated. Use '--ros-args --remap model_states:=model_states_demo' instead.
[gzserver-1] [WARN] [1658992072.131139568] [rcl]: Found remap rule 'link_states:=link_states_demo'. This syntax is deprecated. Use '--ros-args --remap link_states:=link_states_demo' instead.
[gzserver-1] [INFO] [1658992072.134223058] [gazebo_ros_state]: Publishing states of gazebo models at [/model_states_demo]
[gzserver-1] [INFO] [1658992072.134435454] [gazebo_ros_state]: Publishing states of gazebo links at [/link_states_demo]
[spawn_entity.py-5] [INFO] [1658992072.142336157] [spawn_entity]: Calling service /spawn_entity
[spawn_entity.py-5] [INFO] [1658992072.408403612] [spawn_entity]: Spawn status: SpawnEntity: Successfully spawned entity [ip010]
[gzserver-1] [INFO] [1658992072.413851562] [skidbot.imu.imu_plugin]: <initial_orientation_as_reference> is unset, using default value of false to comply with REP 145 (world as orientation reference)
[gzserver-1] [INFO] [1658992072.549176257] [joint_states]: Going to publish joint [l_rear_wheel_joint]
[gzserver-1] [INFO] [1658992072.549210100] [joint_states]: Going to publish joint [r_rear_wheel_joint]
[gzserver-1] [INFO] [1658992072.549216201] [joint_states]: Missing <update_rate>, defaults to 100.000000
[gzserver-1] [INFO] [1658992072.560931288] [diff_drive]: Wheel pair 1 separation set to [0.194000m]
[gzserver-1] [INFO] [1658992072.560961785] [diff_drive]: Wheel pair 1 diameter set to [0.070000m]
[gzserver-1] [INFO] [1658992072.561344849] [diff_drive]: Subscribed to [/cmd_vel]
[gzserver-1] [INFO] [1658992072.562095148] [diff_drive]: Advertise odometry on [/odom]
[gzserver-1] [INFO] [1658992072.562602675] [diff_drive]: Publishing odom transforms between [odom] and [base_footprint]
[INFO] [spawn_entity.py-5]: process has finished cleanly [pid 3086]
### [gzclient   -2] gzclient: /usr/include/boost/smart_ptr/shared_ptr.hpp:734: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = gazebo::rendering::Camera; typename boost::detail::sp_member_access<T>::type = gazebo::rendering::Camera*]: Assertion `px != 0' failed.
[gzclient   -2] Aborted (core dumped)
[ERROR] [gzclient   -2]: process has died [pid 3079, exit code 134, cmd 'gzclient   '].
[INFO] [rviz2-6]: process started with pid [3293]
[rviz2-6] 1658992074.704837 [30]      rviz2: using network interface wlp4s0 (udp/192.168.0.13) selected arbitrarily from: wlp4s0, docker0
[rviz2-6] [INFO] [1658992074.855346011] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-6] [INFO] [1658992074.855540074] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
[rviz2-6] [INFO] [1658992074.879561292] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-6] [INFO] [1658992074.986269172] [rviz2]: Stereo is NOT SUPPORTED

1. aidl_ws 폴더에서 rosfoxy 실행하였습니다

2. 그냥 터미널에서 gazebo를 실행하여도 실행이 되질 않습니다..
해결책 알려주시면 감사하겠습니다!

**Comment by kimsooyoung** [comment]
터미널 상에 아래와 같은 명령어를 입력하신 뒤, 다시 실행해 보세요!

```
source /usr/share/gazebo/setup.sh
```
