### ISSUE TITLE
  LUC에 ROS 다운 받는 중 생긴 에러 질문입니다.

### ISSUE THREAD

**Issue by ghost** [kimsooyoung/AIDL_ip010_lecture#2]
LUC에 20.04를 설치하고 처음부터 다시 진행해보는 중입니다.
아래와 같은 에러가 생기며 설치가 되지 않는데 

aidl@aidl-NUC11BTMi7:~$ sh -c "$(curl -fsSL https://raw.githubusercontent.com/kimsooyoung/ros_menu/main/scripts/setup.sh)"
Installing Neuron Startup Menu...
sh: 7: git: not found
sh: 11: cd: can't cd to /home/aidl/ros_menu
sh: 12: ./install.sh: not found

### (https://github.com/mlcommons/training/issues/327#issuecomment-561325522) •

Try removing the cd so it just runs install.sh
sudo nvidia-docker run -v $(pwd):/workspace -t -i --rm --ipc=host mlperf/object_detection "./install.sh"

이런 방법을 구글링하다 찾았는데 적용해보면 되는건가요~?

**Comment by kimsooyoung** [comment]
```
sh: 7: git: not found
```

위 부분으로 보건데 git이 미설치 되어 있는 것 같습니다.
아래와 같은 커멘드 라인으로 git을 설치해보시겠어요?

```
sudo apt update
sudo apt install git
```

설치 후 확인은 다음과 같습니다.

```
git --version
```
